# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_user_trip'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_joiner',
            field=models.ManyToManyField(related_name='jointrip', to='loginreg.User'),
        ),
    ]
